LDI R16, LOW(RAMEND)
OUT SPL, R16
LDI R16, HIGH(RAMEND)
OUT SPH, R16

.DEF DIVIDEND = R16 
.DEF DIVISOR  = R17
.DEF QUOTIENT = R24
.DEF REMINDER = R25

LDI DIVIDEND, -10
LDI DIVISOR, 7

MOV  R18, DIVIDEND
ANDI R18, 0X80
BREQ POS_DIVIDEND
RJMP NEG_DIVIDEND

POS_DIVIDEND:
MOV  R18, DIVISOR
ANDI R18, 0X80
BREQ POS_DIVISOR_POS_DIVIDEND
RJMP NEG_DIVISOR_POS_DIVIDEND

NEG_DIVIDEND:
MOV  R18, DIVISOR
ANDI R18, 0X80
BREQ POS_DIVISOR_NEG_DIVIDEND
RJMP NEG_DIVISOR_NEG_DIVIDEND

POS_DIVISOR_POS_DIVIDEND:
CALL DIV
RJMP END

NEG_DIVISOR_POS_DIVIDEND:
NEG  DIVISOR
CALL DIV
NEG  QUOTIENT
RJMP END

POS_DIVISOR_NEG_DIVIDEND:
NEG  DIVIDEND
CALL DIV
NEG  QUOTIENT
NEG  DIVIDEND
RJMP END

NEG_DIVISOR_NEG_DIVIDEND:
NEG  DIVIDEND
NEG  DIVISOR
CALL DIV
NEG  DIVIDEND
RJMP END

END:
MOV REMINDER, DIVIDEND
END_: RJMP END_

DIV:
LDI  QUOTIENT, 0X00
START:
SUB  DIVIDEND, DIVISOR
BRCC CONTINUEDIV
ADD  DIVIDEND, DIVISOR
RET
CONTINUEDIV:
INC  QUOTIENT
RJMP START